AllCops:
  TargetRubyVersion: 3.4 # Specify the Ruby version your project uses
  NewCops: enable # Enable new cops by default
  Exclude:
    - 'db/**/*' # Exclude database-related files
    - 'bin/**/*' # Exclude executable scripts
    - 'vendor/**/*' # Exclude third-party libraries

Metrics/CyclomaticComplexity:
  Max: 10